# Generated by Django 3.1 on 2020-10-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20200930_0240'),
        ('main_app', '0010_merge_20200930_0144'),
    ]

    operations = [
    ]
